steps:
  # Step 1: Install Node.js dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Run Expo Prebuild to generate the 'android' folder
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['expo', 'prebuild', '--platform', 'android', '--no-install']

  # Step 3: Build the Android APK using Gradle
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['./gradlew', 'assembleRelease']
    dir: 'android'

  # Step 4: List the generated APKs (for logging/debug)
  - name: 'bash'
    args: ['ls', '-R', 'android/app/build/outputs/apk/']

artifacts:
  objects:
    location: 'gs://glymo-ai-builds/'
    paths: ['android/app/build/outputs/apk/release/*.apk']

options:
  logging: CLOUD_LOGGING_ONLY
