# Trigger Build: Switch to specialized Android build environment
steps:
  # Step 1: Install Node.js dependencies
  - name: 'reactnativecommunity/react-native-android'
    id: 'install-deps'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Run Expo Prebuild
  # We use --no-install because we already did it in Step 1
  - name: 'reactnativecommunity/react-native-android'
    id: 'expo-prebuild'
    entrypoint: 'npx'
    args: ['expo', 'prebuild', '--platform', 'android', '--no-install']

  # Step 3: Fix Gradle permissions & Accept Licenses
  # gradlew needs to be executable on Linux builders
  - name: 'bash'
    id: 'prepare-gradle'
    args:
      - '-c'
      - |
        chmod +x android/gradlew
        # Accept android licenses if sdkmanager is present
        if command -v sdkmanager &> /dev/null; then
          yes | sdkmanager --licenses
        fi

  # Step 4: Build the Android APK using Gradle
  # We use assembleDebug initially to avoid Keystore/Signing errors
  - name: 'gcr.io/cloud-builders/gradle'
    id: 'build-apk'
    args: ['./gradlew', 'assembleDebug']
    dir: 'android'
    env:
      - 'JAVA_OPTS=-Xmx4g' # Give more heap to Gradle

  # Step 5: List the generated APKs
  - name: 'bash'
    id: 'list-artifacts'
    args: ['ls', '-R', 'android/app/build/outputs/apk/']

artifacts:
  objects:
    location: 'gs://glymo-ai-builds/'
    paths: ['android/app/build/outputs/apk/debug/*.apk']

options:
  machineType: 'E2_HIGHCPU_8' # Use a beefy machine to avoid OOM
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s' # 30 minutes timeout
