steps:
  # Step 1: Build & Push and Deploy in one minimal configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'glymo-ai-server'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

timeout: '1200s'
